name: Sync to Second Repo

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Debug PAT_URL
      run: |
         echo "PAT_URL: ${{ secrets.PAT_URL }}"

    - name: Set Up Git
      run: |
        git remote set-url origin https://github.com/Jagrutivk/Second-repo.git  # Replace with the correct URL
        git remote set-url --push origin ${{ secrets.PAT_URL }}
      env:
        PAT_URL: ${{ secrets.PAT_URL }}

    - name: Push to Second Repo
      run: |
        git push origin main  # Adjust the branch name if needed
