name: Sync to Second Repo

on:
 workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote set-url origin https://github.com/Jagrutivk/Second-repo.git  # Replace with the correct URL
        git remote set-url --push origin "https://${{ secrets.PAT_URL }}@github.com/Jagrutivk/Second-repo.git"
      env:
        PAT_URL: ${{ secrets.PAT_URL }}

    - name: Push to Second Repo
      run: |
        git push origin main  # Adjust the branch name if needed
